# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Analytics(_Saas):
    _type = "analytics"
    _icon_dir = "resources/saas/analytics"

class FiveTran(_Analytics):
    _icon = "fivetran.png"

class Mode(_Analytics):
    _icon = "mode.png"

class Snowflake(_Analytics):
    _icon = "snowflake.png"

class Segment(_Analytics):
    _icon = "segment.png"

class Sigma(_Analytics):
    _icon = "sigma.png"

class Stitch(_Analytics):
    _icon = "stitch.png"


# Aliases
