# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Email(_Saas):
    _type = "email"
    _icon_dir = "resources/saas/email"


class Mailgun(_Email):
    _icon = "mailgun.png"


class Vero(_Email):
    _icon = "vero.png"


# Aliases
