# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Logistics(_Saas):
    _type = "logistics"
    _icon_dir = "resources/saas/logistics"


class Dat(_Logistics):
    _icon = "dat.png"


class Freightview(_Logistics):
    _icon = "freightview.png"


class Orderful(_Logistics):
    _icon = "orderful.png"


class P44(_Logistics):
    _icon = "p44.png"


# Aliases
