# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Tms(_Saas):
    _type = "tms"
    _icon_dir = "resources/saas/tms"


class Quickbase(_Tms):
    _icon = "quickbase.png"


# Aliases
